default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  
  password: 'postgres'
  host: localhost
  port: 5432

development:
  <<: *default
  database: atividade_complementar_development
  username: postgres
  password: 'postgres'
  host: localhost
  port: 5432

test:
  <<: *default
  database: atividade_complementar_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: atividade_complementar_production
  username: atividade_complementar
  password: <%= ENV["ATIVIDADE_COMPLEMENTAR_DATABASE_PASSWORD"] %>
